# Generated by Django 4.2.25 on 2025-10-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='伺服器名稱')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 位址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], default='offline', max_length=20, verbose_name='狀態')),
                ('pool_usage', models.FloatField(default=0.0, verbose_name='池使用率 (%)')),
                ('total_leases', models.IntegerField(default=0, verbose_name='總租約數')),
                ('active_leases', models.IntegerField(default=0, verbose_name='活動租約數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'DHCP 伺服器',
                'verbose_name_plural': 'DHCP 伺服器',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DHCPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 位址')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC 位址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主機名稱')),
                ('lease_start', models.DateTimeField(verbose_name='租約開始時間')),
                ('lease_end', models.DateTimeField(verbose_name='租約結束時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活動')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='api.dhcpserver', verbose_name='所屬伺服器')),
            ],
            options={
                'verbose_name': 'DHCP 租約',
                'verbose_name_plural': 'DHCP 租約',
                'ordering': ['-lease_start'],
            },
        ),
    ]
