# Generated by Django 4.2.25 on 2025-10-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpserver',
            name='dhcp_config_path',
            field=models.CharField(default='/etc/dhcp/dhcpd.conf', max_length=500, verbose_name='DHCP 設定檔路徑'),
        ),
        migrations.AddField(
            model_name='dhcpserver',
            name='dhcp_leases_path',
            field=models.CharField(default='/var/lib/dhcp/dhcpd.leases', max_length=500, verbose_name='DHCP Leases 檔案路徑'),
        ),
        migrations.AddField(
            model_name='dhcpserver',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次同步時間'),
        ),
        migrations.AddField(
            model_name='dhcpserver',
            name='ssh_key_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='SSH 金鑰檔案路徑'),
        ),
        migrations.AddField(
            model_name='dhcpserver',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='SSH 密碼'),
        ),
        migrations.AddField(
            model_name='dhcpserver',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='SSH 連接埠'),
        ),
        migrations.AddField(
            model_name='dhcpserver',
            name='ssh_username',
            field=models.CharField(default='root', max_length=100, verbose_name='SSH 使用者名稱'),
        ),
    ]
