# Generated by Django 4.2.25 on 2025-10-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dhcpserver_dhcp_config_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='日誌時間')),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], db_index=True, default='INFO', max_length=10, verbose_name='日誌等級')),
                ('event', models.CharField(blank=True, max_length=30, verbose_name='事件類型')),
                ('message', models.CharField(max_length=200, verbose_name='訊息')),
                ('raw', models.TextField(verbose_name='原始日誌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.dhcpserver', verbose_name='所屬伺服器')),
            ],
            options={
                'verbose_name': 'DHCP 日誌',
                'verbose_name_plural': 'DHCP 日誌',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='idx_server_time'), models.Index(fields=['-timestamp'], name='idx_timestamp'), models.Index(fields=['level'], name='idx_level')],
            },
        ),
    ]
