# Generated by Django 4.2.25 on 2025-10-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dhcplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHCPScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.GenericIPAddressField(verbose_name='Scope ID')),
                ('name', models.CharField(max_length=255, verbose_name='Scope 名稱')),
                ('subnet_mask', models.GenericIPAddressField(verbose_name='子網路遮罩')),
                ('start_range', models.GenericIPAddressField(verbose_name='起始 IP')),
                ('end_range', models.GenericIPAddressField(verbose_name='結束 IP')),
                ('state', models.CharField(choices=[('Active', '啟用'), ('Inactive', '停用')], default='Active', max_length=20, verbose_name='狀態')),
                ('lease_duration', models.CharField(blank=True, max_length=50, verbose_name='租約期限')),
                ('total_addresses', models.IntegerField(default=0, verbose_name='總 IP 數')),
                ('in_use_addresses', models.IntegerField(default=0, verbose_name='已使用 IP 數')),
                ('available_addresses', models.IntegerField(default=0, verbose_name='可用 IP 數')),
                ('usage_percentage', models.FloatField(default=0.0, verbose_name='使用率 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='api.dhcpserver', verbose_name='所屬伺服器')),
            ],
            options={
                'verbose_name': 'DHCP Scope',
                'verbose_name_plural': 'DHCP Scopes',
                'ordering': ['server', 'scope_id'],
                'indexes': [models.Index(fields=['server', 'scope_id'], name='idx_server_scope'), models.Index(fields=['state'], name='idx_scope_state')],
                'unique_together': {('server', 'scope_id')},
            },
        ),
    ]
