# Generated by Django 4.2.25 on 2025-10-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dhcpscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpscope',
            name='end_range',
            field=models.CharField(max_length=45, verbose_name='結束 IP'),
        ),
        migrations.AlterField(
            model_name='dhcpscope',
            name='scope_id',
            field=models.CharField(max_length=45, verbose_name='Scope ID'),
        ),
        migrations.AlterField(
            model_name='dhcpscope',
            name='start_range',
            field=models.CharField(max_length=45, verbose_name='起始 IP'),
        ),
        migrations.AlterField(
            model_name='dhcpscope',
            name='subnet_mask',
            field=models.CharField(max_length=45, verbose_name='子網路遮罩'),
        ),
    ]
