# Generated by Django 4.2.25 on 2025-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dhcpscope_end_range_alter_dhcpscope_scope_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NASConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='記錄時間')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], db_index=True, max_length=10, verbose_name='連線狀態')),
                ('nas_ip', models.GenericIPAddressField(verbose_name='NAS IP')),
                ('nas_share', models.CharField(max_length=100, verbose_name='共享名稱')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='響應時間 (ms)')),
                ('upload_speed', models.FloatField(blank=True, null=True, verbose_name='上傳速度 (MB/s)')),
                ('download_speed', models.FloatField(blank=True, null=True, verbose_name='下載速度 (MB/s)')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': 'NAS 連線記錄',
                'verbose_name_plural': 'NAS 連線記錄',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_nas_timestamp'), models.Index(fields=['status'], name='idx_nas_status'), models.Index(fields=['timestamp', 'status'], name='idx_nas_time_status')],
            },
        ),
    ]
