# Generated by Django 4.2.25 on 2025-10-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nasconnectionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPXELog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='日誌時間')),
                ('log_type', models.CharField(choices=[('mac', 'MAC 管理'), ('boot', 'IPXE 開機')], db_index=True, max_length=10, verbose_name='日誌類型')),
                ('client_ip', models.GenericIPAddressField(verbose_name='客戶端 IP')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP 方法')),
                ('url', models.CharField(max_length=500, verbose_name='請求 URL')),
                ('action', models.CharField(choices=[('Set', 'Set'), ('Get', 'Get'), ('boot.ipxe', 'boot.ipxe'), ('wimboot', 'wimboot'), ('BCD', 'BCD'), ('boot.sdi', 'boot.sdi'), ('wim_file', 'WIM File'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='操作類型')),
                ('status_code', models.IntegerField(verbose_name='HTTP 狀態碼')),
                ('bytes_sent', models.BigIntegerField(verbose_name='傳輸位元組數')),
                ('user_agent', models.CharField(max_length=200, verbose_name='User Agent')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC 位址')),
                ('boot_flag', models.IntegerField(blank=True, null=True, verbose_name='BOOT 旗標')),
                ('file_requested', models.CharField(blank=True, max_length=200, verbose_name='請求的檔案')),
                ('raw', models.TextField(verbose_name='原始日誌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': 'IPXE 日誌',
                'verbose_name_plural': 'IPXE 日誌',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IPXEServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='伺服器名稱')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP 位址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], default='offline', max_length=20, verbose_name='狀態')),
                ('total_requests_today', models.IntegerField(default=0, verbose_name='今日請求總數')),
                ('mac_registrations', models.IntegerField(default=0, verbose_name='MAC 註冊數')),
                ('boot_requests', models.IntegerField(default=0, verbose_name='開機請求數')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH 連接埠')),
                ('ssh_username', models.CharField(default='rvt', max_length=100, verbose_name='SSH 使用者名稱')),
                ('ssh_password', models.CharField(max_length=255, verbose_name='SSH 密碼')),
                ('docker_container_mac', models.CharField(default='ipxe_mac-flask', max_length=100, verbose_name='MAC 管理容器名稱')),
                ('docker_container_ipxe', models.CharField(default='ipxe', max_length=100, verbose_name='IPXE HTTP 容器名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步時間')),
            ],
            options={
                'verbose_name': 'IPXE 伺服器',
                'verbose_name_plural': 'IPXE 伺服器',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPXEStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='統計時間')),
                ('total_requests', models.IntegerField(default=0, verbose_name='總請求數')),
                ('mac_set_count', models.IntegerField(default=0, verbose_name='MAC Set 數量')),
                ('mac_get_count', models.IntegerField(default=0, verbose_name='MAC Get 數量')),
                ('boot_ipxe_count', models.IntegerField(default=0, verbose_name='boot.ipxe 請求數')),
                ('wim_download_count', models.IntegerField(default=0, verbose_name='WIM 下載數')),
                ('total_bytes_sent', models.BigIntegerField(default=0, verbose_name='總傳輸位元組')),
                ('avg_bytes_per_request', models.FloatField(default=0, verbose_name='平均每請求位元組')),
                ('unique_clients', models.IntegerField(default=0, verbose_name='唯一客戶端數')),
                ('unique_macs', models.IntegerField(default=0, verbose_name='唯一 MAC 數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.ipxeserver', verbose_name='所屬伺服器')),
            ],
            options={
                'verbose_name': 'IPXE 統計',
                'verbose_name_plural': 'IPXE 統計',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='ipxeserver',
            index=models.Index(fields=['ip_address'], name='idx_ipxe_server_ip'),
        ),
        migrations.AddIndex(
            model_name='ipxeserver',
            index=models.Index(fields=['status'], name='idx_ipxe_server_status'),
        ),
        migrations.AddField(
            model_name='ipxelog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.ipxeserver', verbose_name='所屬伺服器'),
        ),
        migrations.AddIndex(
            model_name='ipxestatistics',
            index=models.Index(fields=['server', '-timestamp'], name='idx_ipxe_stats_server_time'),
        ),
        migrations.AlterUniqueTogether(
            name='ipxestatistics',
            unique_together={('server', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='ipxelog',
            index=models.Index(fields=['server', '-timestamp'], name='idx_ipxe_log_server_time'),
        ),
        migrations.AddIndex(
            model_name='ipxelog',
            index=models.Index(fields=['-timestamp'], name='idx_ipxe_log_timestamp'),
        ),
        migrations.AddIndex(
            model_name='ipxelog',
            index=models.Index(fields=['log_type'], name='idx_ipxe_log_type'),
        ),
        migrations.AddIndex(
            model_name='ipxelog',
            index=models.Index(fields=['client_ip'], name='idx_ipxe_log_client_ip'),
        ),
        migrations.AddIndex(
            model_name='ipxelog',
            index=models.Index(fields=['mac_address'], name='idx_ipxe_log_mac'),
        ),
    ]
