# Generated by Django 4.2.25 on 2025-10-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ipxelog_ipxeserver_ipxestatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPXENetworkQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='記錄時間')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], db_index=True, max_length=10, verbose_name='連線狀態')),
                ('ping_latency', models.FloatField(blank=True, null=True, verbose_name='Ping 延遲 (ms)')),
                ('ping_packet_loss', models.FloatField(blank=True, null=True, verbose_name='丟包率 (%)')),
                ('http_response_time', models.FloatField(blank=True, null=True, verbose_name='HTTP 響應時間 (ms)')),
                ('http_status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP 狀態碼')),
                ('ssh_response_time', models.FloatField(blank=True, null=True, verbose_name='SSH 響應時間 (ms)')),
                ('ssh_connected', models.BooleanField(default=False, verbose_name='SSH 連線成功')),
                ('download_speed', models.FloatField(blank=True, null=True, verbose_name='下載速度 (MB/s)')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_quality_logs', to='api.ipxeserver', verbose_name='所屬伺服器')),
            ],
            options={
                'verbose_name': 'IPXE 網路品質記錄',
                'verbose_name_plural': 'IPXE 網路品質記錄',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_ipxe_nq_timestamp'), models.Index(fields=['server', '-timestamp'], name='idx_ipxe_nq_server_time'), models.Index(fields=['status'], name='idx_ipxe_nq_status')],
            },
        ),
    ]
