# Generated by Django 4.2.25 on 2025-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ipxenetworkquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcplog',
            name='boot_stage',
            field=models.CharField(blank=True, max_length=50, verbose_name='啟動階段'),
        ),
        migrations.AddField(
            model_name='dhcplog',
            name='client_type',
            field=models.CharField(choices=[('iPXE', 'iPXE'), ('PXE', 'PXE (BIOS)'), ('WinPE', 'Windows PE'), ('OS', 'Operating System'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=20, verbose_name='客戶端類型'),
        ),
        migrations.AddField(
            model_name='dhcplog',
            name='user_class',
            field=models.CharField(blank=True, max_length=200, verbose_name='User Class (Option 77)'),
        ),
        migrations.AddField(
            model_name='dhcplog',
            name='vendor_class',
            field=models.CharField(blank=True, max_length=500, verbose_name='Vendor Class (Option 60)'),
        ),
    ]
