# Generated by Django 4.2.25 on 2025-11-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dhcplog_boot_stage_dhcplog_client_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=255, unique=True, verbose_name='Remote ID (識別碼)')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Switch 名稱')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Switch MAC 地址')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Switch IP 地址')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='實體位置')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='建築物')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='樓層')),
                ('status', models.CharField(choices=[('active', '活躍'), ('inactive', '非活躍'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='狀態')),
                ('total_ports', models.IntegerField(default=0, verbose_name='總端口數')),
                ('active_ports', models.IntegerField(default=0, verbose_name='活動端口數')),
                ('connected_devices', models.IntegerField(default=0, verbose_name='連接設備數')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='首次發現時間')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最後活動時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '網路交換器',
                'verbose_name_plural': '網路交換器',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.CharField(max_length=255, verbose_name='Circuit ID (端口識別碼)')),
                ('port_number', models.CharField(blank=True, max_length=50, verbose_name='端口號')),
                ('port_name', models.CharField(blank=True, max_length=100, verbose_name='端口名稱')),
                ('status', models.CharField(choices=[('up', '啟用'), ('down', '停用'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='狀態')),
                ('connected_devices', models.IntegerField(default=0, verbose_name='連接設備數')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='首次發現時間')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最後活動時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'Switch 端口',
                'verbose_name_plural': 'Switch 端口',
                'ordering': ['switch', 'port_number'],
            },
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='circuit_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Circuit ID (Switch Port)'),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='relay_agent_info',
            field=models.TextField(blank=True, verbose_name='Relay Agent Info (Option 82)'),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remote ID (Switch MAC/ID)'),
        ),
        migrations.AddField(
            model_name='dhcplog',
            name='circuit_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Circuit ID (Switch Port)'),
        ),
        migrations.AddField(
            model_name='dhcplog',
            name='relay_agent_info',
            field=models.TextField(blank=True, verbose_name='Relay Agent Info (Option 82)'),
        ),
        migrations.AddField(
            model_name='dhcplog',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remote ID (Switch MAC/ID)'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['server', 'is_active'], name='idx_lease_server_active'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['remote_id'], name='idx_lease_remote_id'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['circuit_id'], name='idx_lease_circuit_id'),
        ),
        migrations.AddIndex(
            model_name='dhcplog',
            index=models.Index(fields=['remote_id'], name='idx_log_remote_id'),
        ),
        migrations.AddIndex(
            model_name='dhcplog',
            index=models.Index(fields=['circuit_id'], name='idx_log_circuit_id'),
        ),
        migrations.AddField(
            model_name='switchport',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='api.networkswitch', verbose_name='所屬 Switch'),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='dhcp_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='api.dhcpserver', verbose_name='所屬 DHCP Server'),
        ),
        migrations.AddIndex(
            model_name='switchport',
            index=models.Index(fields=['switch', 'circuit_id'], name='idx_port_switch_circuit'),
        ),
        migrations.AddIndex(
            model_name='switchport',
            index=models.Index(fields=['status'], name='idx_port_status'),
        ),
        migrations.AlterUniqueTogether(
            name='switchport',
            unique_together={('switch', 'circuit_id')},
        ),
        migrations.AddIndex(
            model_name='networkswitch',
            index=models.Index(fields=['remote_id'], name='idx_switch_remote_id'),
        ),
        migrations.AddIndex(
            model_name='networkswitch',
            index=models.Index(fields=['mac_address'], name='idx_switch_mac'),
        ),
        migrations.AddIndex(
            model_name='networkswitch',
            index=models.Index(fields=['status'], name='idx_switch_status'),
        ),
        migrations.AddIndex(
            model_name='networkswitch',
            index=models.Index(fields=['dhcp_server'], name='idx_switch_server'),
        ),
    ]
