# Generated by Django 4.2.25 on 2025-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_networkswitch_switchport_dhcplease_circuit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_url', models.CharField(max_length=200, verbose_name='GitLab 網址')),
                ('gitlab_name', models.CharField(default='GitLab Server', max_length=100, verbose_name='伺服器名稱')),
                ('ping_latency', models.FloatField(blank=True, null=True, verbose_name='Ping 延遲 (ms)')),
                ('http_response_time', models.FloatField(blank=True, null=True, verbose_name='HTTP 回應時間 (秒)')),
                ('http_status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP 狀態碼')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='failed', max_length=20, verbose_name='連線狀態')),
                ('is_reachable', models.BooleanField(default=False, verbose_name='是否可達')),
                ('packet_loss', models.FloatField(default=0, verbose_name='封包遺失率 (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='檢查時間')),
            ],
            options={
                'verbose_name': 'GitLab 連線記錄',
                'verbose_name_plural': 'GitLab 連線記錄',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['-checked_at'], name='idx_gitlab_checked'), models.Index(fields=['gitlab_url', '-checked_at'], name='idx_gitlab_url_time'), models.Index(fields=['status'], name='idx_gitlab_status')],
            },
        ),
    ]
