# Generated by Django 4.2.25 on 2025-11-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gitlabconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='伺服器名稱')),
                ('url', models.URLField(max_length=500, verbose_name='Jenkins URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='使用者名稱')),
                ('api_token', models.CharField(blank=True, max_length=500, verbose_name='API Token')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unreachable', 'Unreachable')], default='offline', max_length=20, verbose_name='狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('total_jobs', models.IntegerField(default=0, verbose_name='Job 總數')),
                ('total_builds', models.IntegerField(default=0, verbose_name='Build 總數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步時間')),
            ],
            options={
                'verbose_name': 'Jenkins 伺服器',
                'verbose_name_plural': 'Jenkins 伺服器',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_jenkins_server_status'), models.Index(fields=['is_active'], name='idx_jenkins_server_active')],
            },
        ),
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Job 名稱')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Job 完整路徑')),
                ('url', models.URLField(max_length=1000, verbose_name='Job URL')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_buildable', models.BooleanField(default=True, verbose_name='是否可構建')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否禁用')),
                ('last_build_number', models.IntegerField(blank=True, null=True, verbose_name='最後 Build 編號')),
                ('last_build_status', models.CharField(blank=True, max_length=50, verbose_name='最後 Build 狀態')),
                ('last_build_time', models.DateTimeField(blank=True, null=True, verbose_name='最後 Build 時間')),
                ('total_builds', models.IntegerField(default=0, verbose_name='Build 總數')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='成功率 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步時間')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.jenkinsserver', verbose_name='所屬伺服器')),
            ],
            options={
                'verbose_name': 'Jenkins Job',
                'verbose_name_plural': 'Jenkins Jobs',
                'ordering': ['-last_build_time'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.IntegerField(verbose_name='Build 編號')),
                ('display_name', models.CharField(max_length=200, verbose_name='顯示名稱')),
                ('url', models.URLField(max_length=1000, verbose_name='Build URL')),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('UNSTABLE', 'Unstable'), ('ABORTED', 'Aborted'), ('NOT_BUILT', 'Not Built'), ('BUILDING', 'Building')], default='BUILDING', max_length=20, verbose_name='構建結果')),
                ('is_building', models.BooleanField(default=False, verbose_name='是否正在構建')),
                ('duration', models.BigIntegerField(default=0, verbose_name='構建時長 (ms)')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Build 參數')),
                ('ansible_config', models.JSONField(blank=True, default=dict, verbose_name='Ansible 配置')),
                ('environment_vars', models.JSONField(blank=True, default=dict, verbose_name='環境變數')),
                ('config_file_path', models.CharField(blank=True, max_length=1000, verbose_name='配置文件路徑')),
                ('log_file_path', models.CharField(blank=True, max_length=1000, verbose_name='日誌文件路徑')),
                ('build_timestamp', models.DateTimeField(verbose_name='構建時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記錄建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='記錄更新時間')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='api.jenkinsjob', verbose_name='所屬 Job')),
            ],
            options={
                'verbose_name': 'Jenkins Build',
                'verbose_name_plural': 'Jenkins Builds',
                'ordering': ['-build_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['server', 'name'], name='idx_jenkins_job_server_name'),
        ),
        migrations.AddIndex(
            model_name='jenkinsjob',
            index=models.Index(fields=['last_build_time'], name='idx_jenkins_job_build_time'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsjob',
            unique_together={('server', 'full_name')},
        ),
        migrations.AddIndex(
            model_name='jenkinsbuild',
            index=models.Index(fields=['job', '-build_number'], name='idx_jenkins_build_job_num'),
        ),
        migrations.AddIndex(
            model_name='jenkinsbuild',
            index=models.Index(fields=['result'], name='idx_jenkins_build_result'),
        ),
        migrations.AddIndex(
            model_name='jenkinsbuild',
            index=models.Index(fields=['-build_timestamp'], name='idx_jenkins_build_time'),
        ),
        migrations.AlterUniqueTogether(
            name='jenkinsbuild',
            unique_together={('job', 'build_number')},
        ),
    ]
