# Generated by Django 4.2.25 on 2025-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_jenkinsserver_jenkinsjob_jenkinsbuild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='view_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='所屬 View'),
        ),
    ]
