# Generated by Django 4.2.25 on 2025-11-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_view_name_to_jenkins_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsbuild',
            name='is_workspace_stored',
            field=models.BooleanField(default=False, verbose_name='是否已存儲 Workspace'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='workspace_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Workspace 存儲路徑'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='workspace_size',
            field=models.BigIntegerField(default=0, verbose_name='Workspace 大小 (bytes)'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='workspace_stored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Workspace 存儲時間'),
        ),
    ]
