# Generated by Django 4.2.25 on 2025-11-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jenkinsbuild_is_workspace_stored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsbuild',
            name='failed_stage',
            field=models.CharField(blank=True, max_length=200, verbose_name='失敗的 Stage'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='pipeline_stages',
            field=models.JSONField(blank=True, default=list, verbose_name='Pipeline Stages'),
        ),
    ]
