# Generated by Django 4.2.25 on 2025-11-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_pipeline_stage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsbuild',
            name='failed_stage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='失敗的 Stage'),
        ),
    ]
