# Generated by Django 4.2.25 on 2025-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_allow_null_failed_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsbuild',
            name='pipeline_stages',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Pipeline Stages'),
        ),
    ]
