# Generated by Django 4.2.25 on 2025-11-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_allow_null_pipeline_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipxeserver',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='最後錯誤訊息'),
        ),
        migrations.AlterField(
            model_name='ipxeserver',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('error', 'Error')], default='offline', max_length=20, verbose_name='狀態'),
        ),
    ]
