# Generated by Django 4.2.25 on 2025-11-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_ipxe_server_last_error_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipxeserver',
            name='connection_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('connected', 'Connected'), ('failed', 'Failed'), ('no_containers', 'No Containers'), ('error', 'Error')], default='pending', max_length=20, verbose_name='連接狀態'),
        ),
        migrations.AlterField(
            model_name='ipxeserver',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('error', 'Error'), ('active', 'Active')], default='offline', max_length=20, verbose_name='狀態'),
        ),
    ]
