# Generated by Django 4.2.25 on 2025-11-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ipxeserver_connection_status_alter_ipxeserver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsbuild',
            name='artifacts_count',
            field=models.IntegerField(default=0, verbose_name='Artifacts 檔案數量'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='artifacts_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Artifacts 檔案清單'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='artifacts_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Artifacts 存儲路徑'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='artifacts_size',
            field=models.BigIntegerField(default=0, verbose_name='Artifacts 總大小 (bytes)'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='artifacts_stored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Artifacts 存儲時間'),
        ),
        migrations.AddField(
            model_name='jenkinsbuild',
            name='is_artifacts_stored',
            field=models.BooleanField(default=False, verbose_name='是否已存儲 Artifacts'),
        ),
        migrations.AddIndex(
            model_name='jenkinsbuild',
            index=models.Index(fields=['is_workspace_stored'], name='idx_jenkins_build_ws_stored'),
        ),
        migrations.AddIndex(
            model_name='jenkinsbuild',
            index=models.Index(fields=['is_artifacts_stored'], name='idx_jenkins_build_art_stored'),
        ),
    ]
