# Generated by Django 4.2.26 on 2025-11-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_artifacts_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='記錄時間')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], db_index=True, max_length=10, verbose_name='同步狀態')),
                ('ntp_server', models.GenericIPAddressField(default='10.10.10.51', verbose_name='NTP Server')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='響應時間 (ms)')),
                ('offset', models.FloatField(blank=True, null=True, verbose_name='時間偏移 (ms)')),
                ('stratum', models.IntegerField(blank=True, null=True, verbose_name='Stratum 層級')),
                ('jitter', models.FloatField(blank=True, null=True, verbose_name='時間抖動 (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': 'NTP 同步記錄',
                'verbose_name_plural': 'NTP 同步記錄',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_ntp_timestamp'), models.Index(fields=['status'], name='idx_ntp_status'), models.Index(fields=['timestamp', 'status'], name='idx_ntp_time_status')],
            },
        ),
    ]
