# Generated by Django 4.2.26 on 2025-11-17 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_ntpsynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleHostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='主機名稱')),
                ('groups', models.JSONField(default=list, verbose_name='所屬 Groups')),
                ('ansible_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP 地址')),
                ('ansible_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='SSH 使用者')),
                ('ansible_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='SSH 密碼')),
                ('ansible_port', models.IntegerField(default=22, verbose_name='SSH 端口')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC 地址')),
                ('uart_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='UART 主機')),
                ('other_vars', models.JSONField(default=dict, verbose_name='其他變數')),
                ('validation_status', models.CharField(choices=[('not_checked', '未檢查'), ('passed', '通過'), ('failed', '失敗'), ('warning', '警告')], default='not_checked', max_length=20, verbose_name='驗證狀態')),
                ('validation_results', models.JSONField(default=dict, verbose_name='驗證結果')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='最後驗證時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'Ansible Host 配置',
                'verbose_name_plural': 'Ansible Host 配置',
                'db_table': 'ansible_host_config',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleInventoryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_path', models.CharField(max_length=500, verbose_name='NAS 路徑')),
                ('file_name', models.CharField(default='hosts', max_length=255, verbose_name='檔案名稱')),
                ('status', models.CharField(choices=[('pending', '等待導入'), ('importing', '導入中'), ('success', '導入成功'), ('failed', '導入失敗')], default='pending', max_length=20, verbose_name='狀態')),
                ('syntax_valid', models.BooleanField(default=False, verbose_name='語法有效')),
                ('syntax_error', models.TextField(blank=True, null=True, verbose_name='語法錯誤訊息')),
                ('total_hosts', models.IntegerField(default=0, verbose_name='總 Host 數量')),
                ('total_groups', models.IntegerField(default=0, verbose_name='總 Group 數量')),
                ('is_locked', models.BooleanField(default=False, verbose_name='編輯鎖定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='鎖定時間')),
                ('current_version', models.IntegerField(default=1, verbose_name='當前版本號')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='導入時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_inventories', to=settings.AUTH_USER_MODEL, verbose_name='導入者')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_inventories', to=settings.AUTH_USER_MODEL, verbose_name='鎖定者')),
            ],
            options={
                'verbose_name': 'Ansible Inventory 導入',
                'verbose_name_plural': 'Ansible Inventory 導入記錄',
                'db_table': 'ansible_inventory_import',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', '導入'), ('edit', '編輯'), ('save', '儲存'), ('rollback', '回滾'), ('validate', '驗證')], max_length=20, verbose_name='操作類型')),
                ('changes', models.JSONField(default=dict, verbose_name='變更內容')),
                ('success', models.BooleanField(default=True, verbose_name='操作成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='錯誤訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='來源 IP')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('host_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='api.ansiblehostconfig', verbose_name='相關 Host')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='api.ansibleinventoryimport', verbose_name='所屬 Inventory')),
            ],
            options={
                'verbose_name': 'Inventory 編輯日誌',
                'verbose_name_plural': 'Inventory 編輯日誌',
                'db_table': 'inventory_edit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ansiblehostconfig',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.ansibleinventoryimport', verbose_name='所屬 Inventory'),
        ),
        migrations.CreateModel(
            name='InventoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='版本號')),
                ('backup_file_path', models.CharField(max_length=500, verbose_name='備份檔案路徑')),
                ('content_snapshot', models.TextField(blank=True, null=True, verbose_name='內容快照')),
                ('change_summary', models.TextField(blank=True, null=True, verbose_name='變更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.ansibleinventoryimport', verbose_name='所屬 Inventory')),
            ],
            options={
                'verbose_name': 'Inventory 版本',
                'verbose_name_plural': 'Inventory 版本記錄',
                'db_table': 'inventory_version',
                'ordering': ['-version_number'],
                'unique_together': {('inventory', 'version_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ansiblehostconfig',
            unique_together={('inventory', 'hostname')},
        ),
    ]
