# Generated by Django 4.2.26 on 2025-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ansiblehostconfig_ansibleinventoryimport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMonitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='時間戳記')),
                ('cpu_percent', models.FloatField(verbose_name='CPU 使用率 (%)')),
                ('cpu_count', models.IntegerField(verbose_name='CPU 核心數')),
                ('ram_percent', models.FloatField(verbose_name='記憶體使用率 (%)')),
                ('ram_total_gb', models.FloatField(verbose_name='總記憶體 (GB)')),
                ('ram_used_gb', models.FloatField(verbose_name='已使用記憶體 (GB)')),
                ('ram_available_gb', models.FloatField(verbose_name='可用記憶體 (GB)')),
                ('disk_percent', models.FloatField(verbose_name='磁碟使用率 (%)')),
                ('disk_total_gb', models.FloatField(verbose_name='總磁碟空間 (GB)')),
                ('disk_used_gb', models.FloatField(verbose_name='已使用磁碟空間 (GB)')),
                ('disk_free_gb', models.FloatField(verbose_name='可用磁碟空間 (GB)')),
            ],
            options={
                'verbose_name': '系統監控歷史',
                'verbose_name_plural': '系統監控歷史',
                'db_table': 'system_monitor_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_moni_timesta_a0f865_idx')],
            },
        ),
    ]
