# Generated by Django 4.2.26 on 2025-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_systemmonitorhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmonitorhistory',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='時間戳記'),
        ),
    ]
