# Generated by Django 4.2.26 on 2025-11-20 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_alter_systemmonitorhistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='使用者名稱')),
                ('date', models.DateField(db_index=True, verbose_name='統計日期')),
                ('total_requests', models.IntegerField(default=0, verbose_name='總請求次數')),
                ('get_requests', models.IntegerField(default=0, verbose_name='GET 請求次數')),
                ('post_requests', models.IntegerField(default=0, verbose_name='POST 請求次數')),
                ('put_requests', models.IntegerField(default=0, verbose_name='PUT 請求次數')),
                ('delete_requests', models.IntegerField(default=0, verbose_name='DELETE 請求次數')),
                ('error_count', models.IntegerField(default=0, verbose_name='錯誤次數')),
                ('top_paths', models.JSONField(default=dict, verbose_name='熱門路徑統計')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者活動統計',
                'verbose_name_plural': '使用者活動統計',
                'db_table': 'user_activity',
                'ordering': ['-date', '-total_requests'],
                'indexes': [models.Index(fields=['username', '-date'], name='user_activi_usernam_925e5b_idx'), models.Index(fields=['-date'], name='user_activi_date_2242c4_idx'), models.Index(fields=['-total_requests'], name='user_activi_total_r_72fdb4_idx')],
                'unique_together': {('username', 'date')},
            },
        ),
    ]
