# Generated by Django 4.2.26 on 2025-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='統計日期')),
                ('total_page_views', models.IntegerField(default=0, verbose_name='總頁面瀏覽次數')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='唯一訪客數')),
                ('total_api_requests', models.IntegerField(default=0, verbose_name='API 總請求次數')),
                ('get_requests', models.IntegerField(default=0, verbose_name='GET 請求次數')),
                ('post_requests', models.IntegerField(default=0, verbose_name='POST 請求次數')),
                ('put_requests', models.IntegerField(default=0, verbose_name='PUT 請求次數')),
                ('delete_requests', models.IntegerField(default=0, verbose_name='DELETE 請求次數')),
                ('dashboard_visits', models.IntegerField(default=0, verbose_name='Dashboard 訪問次數')),
                ('dhcp_page_visits', models.IntegerField(default=0, verbose_name='DHCP 頁面訪問次數')),
                ('ipxe_page_visits', models.IntegerField(default=0, verbose_name='iPXE 頁面訪問次數')),
                ('jenkins_page_visits', models.IntegerField(default=0, verbose_name='Jenkins 頁面訪問次數')),
                ('ansible_page_visits', models.IntegerField(default=0, verbose_name='Ansible 頁面訪問次數')),
                ('dhcp_sync_count', models.IntegerField(default=0, verbose_name='DHCP 同步次數')),
                ('ipxe_operations', models.IntegerField(default=0, verbose_name='iPXE 操作次數')),
                ('jenkins_builds', models.IntegerField(default=0, verbose_name='Jenkins Build 觸發次數')),
                ('ansible_executions', models.IntegerField(default=0, verbose_name='Ansible 執行次數')),
                ('error_count', models.IntegerField(default=0, verbose_name='錯誤次數')),
                ('error_4xx', models.IntegerField(default=0, verbose_name='4xx 錯誤次數')),
                ('error_5xx', models.IntegerField(default=0, verbose_name='5xx 錯誤次數')),
                ('top_pages', models.JSONField(default=dict, verbose_name='熱門頁面統計')),
                ('top_api_endpoints', models.JSONField(default=dict, verbose_name='熱門 API 端點統計')),
                ('top_users', models.JSONField(default=list, verbose_name='最活躍使用者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '網站使用統計',
                'verbose_name_plural': '網站使用統計',
                'db_table': 'website_usage_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.AddIndex(
            model_name='websiteusagestats',
            index=models.Index(fields=['-date'], name='website_usa_date_577bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteusagestats',
            index=models.Index(fields=['-total_page_views'], name='website_usa_total_p_ef9763_idx'),
        ),
    ]
