# Generated by Django 4.2.26 on 2025-11-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_websiteusagestats_delete_useractivity_and_more'),
    ]

    operations = [
    ]
