# Generated by Django 4.2.26 on 2025-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_is_building_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTPSyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作時間')),
                ('ntp_server', models.CharField(default='10.10.10.51', max_length=100, verbose_name='NTP 服務器')),
                ('sync_method', models.CharField(choices=[('ntpdate', 'ntpdate'), ('chrony', 'chronyd'), ('manual', 'Manual')], default='ntpdate', max_length=20, verbose_name='同步方法')),
                ('offset_before', models.FloatField(help_text='同步前系統時間與 NTP 服務器的偏移量', verbose_name='同步前偏移 (ms)')),
                ('offset_after', models.FloatField(blank=True, help_text='同步後系統時間與 NTP 服務器的偏移量', null=True, verbose_name='同步後偏移 (ms)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='狀態')),
                ('duration', models.FloatField(blank=True, help_text='同步操作耗時', null=True, verbose_name='執行時間 (秒)')),
                ('command_output', models.TextField(blank=True, help_text='ntpdate 或 chrony 命令的輸出', verbose_name='命令輸出')),
                ('error_message', models.TextField(blank=True, help_text='同步失敗時的錯誤描述', verbose_name='錯誤訊息')),
                ('triggered_by', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('alert', 'Alert')], db_index=True, default='auto', help_text='auto: 自動觸發, manual: 手動觸發, alert: 告警觸發', max_length=50, verbose_name='觸發方式')),
                ('sync_decision_reason', models.TextField(blank=True, help_text='為什麼執行此次同步（例如：偏移超過閾值 200ms）', verbose_name='同步決策原因')),
                ('improvement', models.FloatField(blank=True, help_text='同步前後偏移量的改善值', null=True, verbose_name='改善量 (ms)')),
            ],
            options={
                'verbose_name': 'NTP 同步操作',
                'verbose_name_plural': 'NTP 同步操作',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_ntp_op_timestamp'), models.Index(fields=['status'], name='idx_ntp_op_status'), models.Index(fields=['triggered_by'], name='idx_ntp_op_trigger'), models.Index(fields=['-timestamp', 'status'], name='idx_ntp_op_time_status')],
            },
        ),
    ]
