# Generated by Django 4.2.26 on 2025-12-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_ntp_sync_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency_ms', models.FloatField(help_text='Ping 往返時間（平均值）', verbose_name='延遲 (ms)')),
                ('latency_min_ms', models.FloatField(blank=True, null=True, verbose_name='最小延遲 (ms)')),
                ('latency_max_ms', models.FloatField(blank=True, null=True, verbose_name='最大延遲 (ms)')),
                ('packet_loss', models.FloatField(help_text='0-100 的百分比值', verbose_name='封包遺失率 (%)')),
                ('jitter_ms', models.FloatField(blank=True, help_text='延遲變化程度 (mdev)', null=True, verbose_name='抖動 (ms)')),
                ('is_reachable', models.BooleanField(default=True, verbose_name='是否可達')),
                ('packets_sent', models.IntegerField(default=5, verbose_name='發送封包數')),
                ('packets_received', models.IntegerField(default=5, verbose_name='接收封包數')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記錄時間')),
                ('dhcp_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_quality_records', to='api.dhcpserver', verbose_name='DHCP Server')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_quality_records', to='api.networkswitch', verbose_name='Switch')),
            ],
            options={
                'verbose_name': '網路品質記錄',
                'verbose_name_plural': '網路品質記錄',
                'db_table': 'network_quality_record',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['dhcp_server', 'switch', 'recorded_at'], name='idx_nq_server_switch_time'), models.Index(fields=['dhcp_server', 'recorded_at'], name='idx_nq_server_time'), models.Index(fields=['switch', 'recorded_at'], name='idx_nq_switch_time'), models.Index(fields=['recorded_at'], name='idx_nq_recorded_at'), models.Index(fields=['is_reachable'], name='idx_nq_reachable')],
            },
        ),
    ]
