# Generated by Django 4.2.26 on 2025-12-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_network_quality_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='current_branch',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='目前分支'),
        ),
    ]
